image: node:latest

stages:
  - install
  - build
  - deploy

before_script:
  - PACKAGE_VERSION=$(node -p "require('./package.json').version")

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  username: "rahulrrai"

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 60 mins

deploy:
  stage: deploy
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - aws configure set region us-east-1
    - aws s3 cp build s3://deepaksoni.net --recursive
  only:
    refs:
      - tags
      - master
