image: node:latest

stages:
  - install
  - build
  - deploy

before_script:
  - PACKAGE_VERSION=$(node -p "require('./package.json').version")

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  username: "rahulrrai"

install:
  stage: install
  script:
    - npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build
    expire_in: 60 mins
  dependencies:
    - install

.deploy:
  stage: deploy
  script:
    - git clone --depth 1 https://$username:$GITHUB_ACCESS_TOKEN@github.com/$username/$username.github.io.git
    - mkdir $username.github.io.new
    - cp -a $username.github.io/.git $username.github.io.new/.git
    - cp -a build/* $username.github.io.new
    - cd $username.github.io.new
    - git config user.email "rahulrrai19@gmail.com"
    - git config --global user.name "Rahul Rai"
    - git add -A
    - git diff-index --quiet HEAD || git commit -m "$PACKAGE_VERSION $CI_PIPELINE_ID"
    - git push
  artifacts:
    paths:
    - build
